<a href="https://colab.research.google.com/github/tareknahool/Data-Analysis/blob/master/_code_file__CH01_NumPy_Library_Mhara_tek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_array=np.array([10,20,30,40])
print(my_array)

[10 20 30 40]


In [3]:
print(type(my_array))
print(my_array.shape)

<class 'numpy.ndarray'>
(4,)


"what does the (4,) means ?\n",
        "it identifies the number of rows this numpy array contains , ie: 4x1 array or in others words first class array       

 "to change an element in the numpy array , simply refere to the element index and assign the your desired value "

In [4]:
 my_array[0]=15
print(my_array)

[15 20 30 40]


 "whats numpy ?
        
"its a main library in python that deals with scientific computing,
it provides high performance multi-dimensional array object ie: can deal with more than one dimensional array (2x2, 3x3....etc),
    not only but also it facilitates the use of the mathematical operations in case of dealing with such arrays,
        

"traditional arrays(python_lists) vs Numpy arrays
"The main benefits of using NumPy arrays should be smaller memory consumption and better runtime behavior.      

In [5]:
import numpy as np 
#define an array of numpy
my_array=np.array([10,20,30,40])
print(my_array)
print(type(my_array))
print(my_array.shape) 
# to change ana element in the numpy array , simply refere to the element index and assign the your desired value "
my_array[0]=15
print(my_array)
# now lets create a multi-dimensional array of dimensions (rank 2 )"
my_new_array=np.array([[10,20,30,40],[50,60,70,80]])
print(my_new_array)
print(type(my_new_array))
print(my_new_array.shape)
# "what if we want to print 2x2 array in numpy ?"
x=np.array([[1,2],[3,4]])
print (x)
print(x.shape)
# **Indexing and Slicing Arrays**"
#"refering to index-value ,"it means that we want to call a value by its index , let us see how this is done"
y=np.array([1,2,3,4,5,6,7])
print(y)
print (y.shape )
#let us print the first element of this numpy array denoted by the index zero ",
#just a reminder the element in the array = index-1",
#element value which is equal to one is considered the first element in the numpy",
#with index of zero",
#"print(\"first element in the numpy array:\",y[0])",
#if we want to print elements from index 0 to 3\n",
#print(\"first three elements are\",y[0:3])"
# **Creating Automatic Arrays**",
# "1.   creating zeros array",
# "2.   creating ones arrayn",
# "3.   creating constant_type arrays",
# "4.   creating identity array(identity_matrix)",
# "5.   creating random_type_arrays",
#creating an automatic_zeros_array",
zero_array=np.zeros((3,3))
print(zero_array)
#creating an automatic ones array",
one_array=np.ones((3,3))
print(one_array)
#creating constant type array, here we should choose a number that will be constant 
#and pass it to the numpy array , i choose here no.7,
c_array=np.full((3,3),7)
print(c_array)
#the identity matrix eye_array
eye_matrix=np.eye(3)
print(eye_matrix)
#the random array",
R=np.random.random((3,3))
print(R[0:2])
# **NumPy Data Types** ",
# we will go for now for 3 main data types in numbers(we wont talk about strings now)",
# "1.   integers ",
# "2.   floats ( pointed numbers )",
# "3.   complex numbers ( rarely used in our course)

[10 20 30 40]
<class 'numpy.ndarray'>
(4,)
[15 20 30 40]
[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
(2, 4)
[[1 2]
 [3 4]]
(2, 2)
[1 2 3 4 5 6 7]
(7,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.02537649 0.01346675 0.9530552 ]
 [0.40576591 0.9117686  0.91799261]]


In [6]:
import numpy as np
x = np.array([1, 2])   # Let numpy choose the datatype",
print(x.dtype)         # Prints \"int64\"\n",
x = np.array([1.0, 2.0])   # Let numpy choose the datatype",
print(x.dtype)             # Prints \"float64\",
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype",
print(x.dtype) 
# **Basic Mathematical Operations (arithmatic operations )**
import numpy as np
x = np.array([[10,20],[30,40]], dtype=np.float64)
y = np.array([[50,60],[70,80]], dtype=np.float64)
print(x.shape)
print(y.shape)
print(x + y)
print(np.add(x, y))
# "the arithmatic add operation can give the same result in both usage "
print(x - y)
print(np.subtract(x, y))
# "the arithmatic minus operation can give the same result in both usage "
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))
# **More Operations on Arrays:**\n",
#" (Dot product, Transpose, Broadcasting)"
# **1. Dot product versus element wise multiplication**\n"
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
print(v.shape)
print(v.dot(w))
print(x.dot(v))
print(x.dot(y))
# "**2. Transpose**"
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(x.T)
v=np.array([1,2,3])
print(v)
print(v.T)
print(v.shape)
# "**3. Broadcasting**
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
vv=np.tile(v,(4,1))
print(vv)
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
sum_of_vectors=x+v
print(sum_of_vectors)

int64
float64
int64
(2, 2)
(2, 2)
[[ 60.  80.]
 [100. 120.]]
[[ 60.  80.]
 [100. 120.]]
[[-40. -40.]
 [-40. -40.]]
[[-40. -40.]
 [-40. -40.]]
[[ 500. 1200.]
 [2100. 3200.]]
[[ 500. 1200.]
 [2100. 3200.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]
(2,)
219
[29 67]
[[19 22]
 [43 50]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
(3,)
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
